services:
  - type: web
    name: agri-coop
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL_CA
        value: /opt/render/project/src/config/aiven-ca.pem
      - key: BASE_URL
        sync: false
      - key: APP_NAME
        value: FARCO
